name: Lint Markdown

on:
  push:
    branches:
      - master
      - 'stable-*'
      - 'dev-*'
    paths: ['**.md', '.markdownlint*']
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.repository == 'TrustTunnel/TrustTunnel'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Lint Markdown
        run: |
          npm install -g markdownlint-cli
          make lint-md
