name: Lint Rust

on:
  push:
    branches:
      - master
      - 'stable-*'
      - 'dev-*'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.repository == 'TrustTunnel/TrustTunnel'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Rust
        run: rustup toolchain install 1.95 --profile minimal --component rustfmt,clippy
      - name: Lint Rust
        run: make lint-rust
