name: Security audit

on:
  push:
    branches:
      - master
      - 'stable-*'
    paths: ['**/Cargo.toml', '**/Cargo.lock']
  pull_request:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    if: github.repository == 'TrustTunnel/TrustTunnel'
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Audit
        uses: actions-rust-lang/audit@v1
